import { useState, useEffect, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import {
  Bot, Eye, TrendingUp, BarChart3, Calendar, ArrowLeft,
  Loader2, RefreshCw, FileText, Clock, Filter, X
} from "lucide-react";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow
} from "@/components/ui/table";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue
} from "@/components/ui/select";
import {
  Popover, PopoverContent, PopoverTrigger
} from "@/components/ui/popover";
import { Calendar as CalendarPicker } from "@/components/ui/calendar";
import { cn } from "@/lib/utils";
import { format } from "date-fns";
import { de } from "date-fns/locale";
import {
  PieChart, Pie, Cell, ResponsiveContainer, BarChart, Bar,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend
} from "recharts";

interface AutoPost {
  id: string;
  title: string;
  slug: string;
  topic: string;
  topic_color: string;
  published_at: string;
  view_count: number;
  like_count: number;
  comment_count: number;
  read_time: number;
  hero_image_url: string | null;
  status: string;
}

const CHART_COLORS = [
  "hsl(var(--primary))",
  "hsl(var(--accent))",
  "#f59e0b",
  "#10b981",
  "#8b5cf6",
  "#ec4899",
  "#06b6d4",
  "#f97316",
];

const AdminAutoGeneratedPosts = () => {
  const [posts, setPosts] = useState<AutoPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [profile, setProfile] = useState<any>(null);
  const navigate = useNavigate();

  // Filter state
  const [filterCategory, setFilterCategory] = useState<string>("all");
  const [filterStatus, setFilterStatus] = useState<string>("all");
  const [filterDateFrom, setFilterDateFrom] = useState<Date | undefined>(undefined);
  const [filterDateTo, setFilterDateTo] = useState<Date | undefined>(undefined);

  useEffect(() => {
    const checkAuth = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) { navigate("/auth", { replace: true }); return; }
      const { data: p } = await supabase
        .from("profiles").select("*").eq("id", session.user.id).maybeSingle();
      if (!p || p.role !== "admin") {
        toast.error("Zugriff verweigert");
        navigate("/", { replace: true });
        return;
      }
      setProfile(p);
    };
    checkAuth();
  }, [navigate]);

  const fetchPosts = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("blog_posts")
      .select("id, title, slug, topic, topic_color, published_at, view_count, like_count, comment_count, read_time, hero_image_url, status")
      .order("published_at", { ascending: false });

    if (error) {
      toast.error("Fehler beim Laden");
    } else {
      setPosts((data as AutoPost[]) || []);
    }
    setLoading(false);
  };

  useEffect(() => {
    if (profile) fetchPosts();
  }, [profile]);

  const triggerGeneration = async () => {
    setGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("auto-generate-daily-post", { body: {} });
      if (error) throw error;
      if (data?.success) {
        toast.success(`Neuer Artikel: "${data.title}"`);
        fetchPosts();
      } else throw new Error(data?.error || "Fehler");
    } catch (err) {
      toast.error((err as Error).message);
    } finally {
      setGenerating(false);
    }
  };

  // Available categories from data
  const availableCategories = useMemo(() => {
    const set = new Set(posts.map(p => p.topic));
    return Array.from(set).sort();
  }, [posts]);

  // Available statuses from data
  const availableStatuses = useMemo(() => {
    const set = new Set(posts.map(p => p.status));
    return Array.from(set).sort();
  }, [posts]);

  // Filtered posts
  const filteredPosts = useMemo(() => {
    return posts.filter(p => {
      if (filterCategory !== "all" && p.topic !== filterCategory) return false;
      if (filterStatus !== "all" && p.status !== filterStatus) return false;
      if (filterDateFrom && p.published_at && new Date(p.published_at) < filterDateFrom) return false;
      if (filterDateTo) {
        const endOfDay = new Date(filterDateTo);
        endOfDay.setHours(23, 59, 59, 999);
        if (p.published_at && new Date(p.published_at) > endOfDay) return false;
      }
      return true;
    });
  }, [posts, filterCategory, filterStatus, filterDateFrom, filterDateTo]);

  const hasActiveFilters = filterCategory !== "all" || filterStatus !== "all" || filterDateFrom || filterDateTo;

  const clearFilters = () => {
    setFilterCategory("all");
    setFilterStatus("all");
    setFilterDateFrom(undefined);
    setFilterDateTo(undefined);
  };

  // Stats based on filtered posts
  const totalViews = useMemo(() => filteredPosts.reduce((s, p) => s + (p.view_count || 0), 0), [filteredPosts]);
  const totalPosts = filteredPosts.length;
  const avgViews = totalPosts ? Math.round(totalViews / totalPosts) : 0;

  // Category distribution from filtered posts
  const categoryData = useMemo(() => {
    const map: Record<string, number> = {};
    filteredPosts.forEach(p => { map[p.topic] = (map[p.topic] || 0) + 1; });
    return Object.entries(map)
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value);
  }, [filteredPosts]);

  // Monthly generation timeline from filtered posts
  const timelineData = useMemo(() => {
    const months: Record<string, { month: string; count: number; views: number }> = {};
    filteredPosts.forEach(p => {
      if (!p.published_at) return;
      const d = new Date(p.published_at);
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
      const label = d.toLocaleDateString("de-DE", { month: "short", year: "2-digit" });
      if (!months[key]) months[key] = { month: label, count: 0, views: 0 };
      months[key].count++;
      months[key].views += p.view_count || 0;
    });
    return Object.entries(months)
      .sort(([a], [b]) => a.localeCompare(b))
      .slice(-6)
      .map(([, v]) => v);
  }, [filteredPosts]);

  if (!profile) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <span className="text-muted-foreground animate-pulse">Überprüfe Berechtigung...</span>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-muted/30">
      <div className="container max-w-7xl mx-auto py-8 px-4 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" onClick={() => navigate("/admin/blog")}>
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <div>
              <h1 className="text-2xl font-bold flex items-center gap-2">
                <Bot className="h-6 w-6 text-primary" />
                Auto-Pilot Übersicht
              </h1>
              <p className="text-sm text-muted-foreground">
                Alle generierten Artikel mit Statistiken & Kategorie-Verteilung
              </p>
            </div>
          </div>
          <Button onClick={triggerGeneration} disabled={generating}>
            {generating ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <RefreshCw className="h-4 w-4 mr-2" />}
            Jetzt generieren
          </Button>
        </div>

        {/* Filter Bar */}
        <Card>
          <CardContent className="pt-5 pb-4">
            <div className="flex flex-wrap items-end gap-3">
              <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
                <Filter className="h-4 w-4" />
                Filter
              </div>

              {/* Category Filter */}
              <div className="space-y-1">
                <label className="text-xs text-muted-foreground">Kategorie</label>
                <Select value={filterCategory} onValueChange={setFilterCategory}>
                  <SelectTrigger className="w-[180px] h-9">
                    <SelectValue placeholder="Alle Kategorien" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Alle Kategorien</SelectItem>
                    {availableCategories.map(cat => (
                      <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Status Filter */}
              <div className="space-y-1">
                <label className="text-xs text-muted-foreground">Status</label>
                <Select value={filterStatus} onValueChange={setFilterStatus}>
                  <SelectTrigger className="w-[150px] h-9">
                    <SelectValue placeholder="Alle Status" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Alle Status</SelectItem>
                    {availableStatuses.map(s => (
                      <SelectItem key={s} value={s}>
                        {s === "published" ? "Live" : s === "draft" ? "Entwurf" : s}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Date From */}
              <div className="space-y-1">
                <label className="text-xs text-muted-foreground">Von</label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      className={cn(
                        "w-[150px] h-9 justify-start text-left font-normal text-sm",
                        !filterDateFrom && "text-muted-foreground"
                      )}
                    >
                      <Calendar className="h-3.5 w-3.5 mr-1.5" />
                      {filterDateFrom ? format(filterDateFrom, "dd.MM.yyyy") : "Startdatum"}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0" align="start">
                    <CalendarPicker
                      mode="single"
                      selected={filterDateFrom}
                      onSelect={setFilterDateFrom}
                      locale={de}
                      initialFocus
                      className={cn("p-3 pointer-events-auto")}
                    />
                  </PopoverContent>
                </Popover>
              </div>

              {/* Date To */}
              <div className="space-y-1">
                <label className="text-xs text-muted-foreground">Bis</label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      className={cn(
                        "w-[150px] h-9 justify-start text-left font-normal text-sm",
                        !filterDateTo && "text-muted-foreground"
                      )}
                    >
                      <Calendar className="h-3.5 w-3.5 mr-1.5" />
                      {filterDateTo ? format(filterDateTo, "dd.MM.yyyy") : "Enddatum"}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0" align="start">
                    <CalendarPicker
                      mode="single"
                      selected={filterDateTo}
                      onSelect={setFilterDateTo}
                      locale={de}
                      initialFocus
                      className={cn("p-3 pointer-events-auto")}
                    />
                  </PopoverContent>
                </Popover>
              </div>

              {/* Clear Filters */}
              {hasActiveFilters && (
                <Button variant="ghost" size="sm" onClick={clearFilters} className="h-9">
                  <X className="h-3.5 w-3.5 mr-1" />
                  Zurücksetzen
                </Button>
              )}
            </div>

            {hasActiveFilters && (
              <p className="text-xs text-muted-foreground mt-2">
                {filteredPosts.length} von {posts.length} Artikeln angezeigt
              </p>
            )}
          </CardContent>
        </Card>

        {/* KPI Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <FileText className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{totalPosts}</p>
                  <p className="text-xs text-muted-foreground">Artikel gesamt</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <Eye className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{totalViews.toLocaleString("de-DE")}</p>
                  <p className="text-xs text-muted-foreground">Views gesamt</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <TrendingUp className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{avgViews.toLocaleString("de-DE")}</p>
                  <p className="text-xs text-muted-foreground">⌀ Views/Artikel</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <BarChart3 className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{categoryData.length}</p>
                  <p className="text-xs text-muted-foreground">Kategorien</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Charts Row */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Kategorie-Verteilung</CardTitle>
            </CardHeader>
            <CardContent>
              {categoryData.length > 0 ? (
                <div className="flex items-center gap-4">
                  <ResponsiveContainer width="50%" height={220}>
                    <PieChart>
                      <Pie
                        data={categoryData}
                        dataKey="value"
                        nameKey="name"
                        cx="50%"
                        cy="50%"
                        outerRadius={80}
                        innerRadius={40}
                      >
                        {categoryData.map((_, i) => (
                          <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} />
                        ))}
                      </Pie>
                      <Tooltip />
                    </PieChart>
                  </ResponsiveContainer>
                  <div className="space-y-1.5 text-sm flex-1">
                    {categoryData.map((c, i) => (
                      <div key={c.name} className="flex items-center gap-2">
                        <div
                          className="w-3 h-3 rounded-full shrink-0"
                          style={{ backgroundColor: CHART_COLORS[i % CHART_COLORS.length] }}
                        />
                        <span className="truncate">{c.name}</span>
                        <span className="ml-auto font-medium text-muted-foreground">{c.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                <p className="text-muted-foreground text-sm">Keine Daten</p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <Calendar className="h-4 w-4" />
                Generierungs-Historie
              </CardTitle>
            </CardHeader>
            <CardContent>
              {timelineData.length > 0 ? (
                <ResponsiveContainer width="100%" height={220}>
                  <BarChart data={timelineData}>
                    <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                    <XAxis dataKey="month" className="text-xs" />
                    <YAxis className="text-xs" />
                    <Tooltip />
                    <Legend />
                    <Bar dataKey="count" name="Artikel" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
                    <Bar dataKey="views" name="Views" fill="hsl(var(--accent))" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              ) : (
                <p className="text-muted-foreground text-sm">Keine Daten</p>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Articles Table */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">
              {hasActiveFilters
                ? `Gefilterte Artikel (${filteredPosts.length} von ${posts.length})`
                : `Alle Artikel (${totalPosts})`}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            ) : filteredPosts.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                <Filter className="h-8 w-8 mx-auto mb-2 opacity-40" />
                <p>Keine Artikel für diese Filter gefunden.</p>
                {hasActiveFilters && (
                  <Button variant="link" size="sm" onClick={clearFilters} className="mt-1">
                    Filter zurücksetzen
                  </Button>
                )}
              </div>
            ) : (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Titel</TableHead>
                      <TableHead>Kategorie</TableHead>
                      <TableHead className="text-right">Views</TableHead>
                      <TableHead className="text-right">Lesezeit</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Datum</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredPosts.map(post => (
                      <TableRow key={post.id} className="cursor-pointer hover:bg-muted/50"
                        onClick={() => window.open(`/blog/${post.slug}`, "_blank")}
                      >
                        <TableCell className="font-medium max-w-xs truncate">
                          {post.title}
                        </TableCell>
                        <TableCell>
                          <Badge variant="secondary" className="text-xs">
                            {post.topic}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right tabular-nums">
                          <span className="flex items-center justify-end gap-1">
                            <Eye className="h-3 w-3 text-muted-foreground" />
                            {(post.view_count || 0).toLocaleString("de-DE")}
                          </span>
                        </TableCell>
                        <TableCell className="text-right tabular-nums">
                          <span className="flex items-center justify-end gap-1">
                            <Clock className="h-3 w-3 text-muted-foreground" />
                            {post.read_time} min
                          </span>
                        </TableCell>
                        <TableCell>
                          <Badge variant={post.status === "published" ? "default" : "outline"} className="text-xs">
                            {post.status === "published" ? "Live" : post.status}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-muted-foreground text-sm whitespace-nowrap">
                          {post.published_at
                            ? new Date(post.published_at).toLocaleDateString("de-DE", {
                                day: "2-digit", month: "2-digit", year: "numeric"
                              })
                            : "–"}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default AdminAutoGeneratedPosts;
