
-- Erstelle neuen Blogartikel zum Thema Türen & vernetze ihn mit der Kategorie "Fenster und Türen"
INSERT INTO blog_posts (
    title,
    slug,
    excerpt,
    content,
    category_id,
    author_id,
    status,
    cover_url,
    hero_image_url,
    topic,
    topic_color,
    published_at,
    read_time,
    seo_title,
    seo_description,
    keywords,
    table_of_contents,
    difficulty,
    savings_potential,
    payback_time,
    funding_available,
    effort_level,
    key_benefits,
    important_notice,
    costs,
    is_featured
) VALUES (
    'Moderne Türen: Sicherheit, Energieeffizienz und Design im Überblick',
    'moderne-tueren-vergleich',
    'Alles rund um Haustüren, Zimmertüren und wie sie Sicherheit, Energieeffizienz und das Wohngefühl verbessern – Tipps zur Auswahl und zu Fördermöglichkeiten.',
    '<h2>Warum sind Türen wichtiger als gedacht?</h2><p>Türen bestimmen nicht nur das Design Ihres Zuhauses, sie sind auch ein entscheidender Faktor für Sicherheit, Energieeinsparung und Wohnkomfort.</p><h3>1. Haustüren: Schutz & Visitenkarte</h3><p>Die Haustür ist das Aushängeschild Ihres Hauses und die erste Barriere gegen Einbrecher. Moderne Türen setzen auf Mehrfachverriegelung, massive Sicherheitszylinder und innovative Materialien wie Stahl, Aluminium oder Holz-Verbundstoffe. Ihre Wärmedämmwerte (Ud-Wert) tragen auch zur Energieeffizienz bei.</p><h3>2. Innentüren: Wohnkomfort & Akustik</h3><p>Innentüren strukturieren Räume und sorgen für Ruhe. Besonders gefragt sind schalldämmende Türen oder Modelle mit Glaselementen für mehr Tageslicht. </p><h3>3. Energie sparen mit passenden Türen</h3><p>Alte Türen sind oft Wärmebrücken. Moderne Türen punkten mit Mehrkammerprofilen, speziellen Dichtungen und thermischer Trennung im Türblatt. Ein Austausch kann bis zu 10% Heizkosten sparen!</p><h3>4. Fördermöglichkeiten</h3><p>Zuschüsse gibt es häufig für einbruchsichere sowie energieeffiziente Haustüren – teils im Rahmen der KfW, BAFA oder Landesprogramme. <a href="/foerdermittel">Zu den aktuellen Fördermitteln →</a></p><img src="https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&h=600&fit=crop" alt="Moderne Haustür in Holzoptik"/><h3>5. Trends & Design</h3><p>Farben, Oberflächen und Smart Home: Beliebt sind fingerabdruckgesteuerte Türsysteme, verdeckt liegende Bänder sowie individuelle Designs – vom Landhausstil bis minimalistisch. Türen können heute echte Unikate sein.</p><h3>6. Worauf achten beim Kauf?</h3><ul><li>Wärmedämmwert (Ud)</li><li>Sicherheitsklasse (RC-Wert)</li><li>Materialauswahl</li><li>Professioneller Einbau</li></ul><hr/><h3>Weitere Ratgeber</h3><ul><li><a href="/fenster-tueren">Zum Portal Fenster & Türen</a></li><li><a href="/blog/daemmstoffe-vergleich-2025">Dämmstoffe im Überblick</a></li><li><a href="/smart-home">Smart Home Lösungen</a></li></ul>',
    (SELECT id FROM blog_categories WHERE slug = 'fenster-tueren'),
    (SELECT id FROM blog_authors LIMIT 1),
    'published',
    'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&h=600&fit=crop',
    'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1200&h=800&fit=crop',
    'Fenster & Türen',
    '#0ea5e9',
    NOW(),
    7,
    'Moderne Türen: Sicherheit, Förderung & Trends',
    'Alle Infos zu Haustüren, Zimmertüren, Sicherheit, Energieeffizienz und Design. Inkl. Fördermittel – Jetzt informieren!',
    ARRAY['Türen Vergleich', 'Haustüren', 'Zimmertüren', 'Energieeffizienz', 'Sicherheit', 'KfW Förderung'],
    '[{"id":"warum-tueren","title":"Warum Türen wichtig sind"},{"id":"haustuer","title":"Die sichere Haustür"},{"id":"innentuer","title":"Innentüren & Akustik"},{"id":"energie-effizienz","title":"Energieeffizienz"},{"id":"foerderung","title":"Fördermöglichkeiten"},{"id":"trends","title":"Trends & Design"},{"id":"kauftipps","title":"Tipps zum Kauf"}]',
    2,
    'Bis zu 10% Heizkosten sparen',
    '5-10 Jahre',
    'Ja – KfW, BAFA & Länder',
    'Niedrig bis mittel',
    ARRAY['Mehr Sicherheit', 'Weniger Energieverlust', 'Design nach Wunsch'],
    'Für Förderungen auf richtige Reihenfolge achten: Antrag immer vor Einbau!',
    '[{"item": "Haustür", "costPerSqm": "600€", "totalCost": "3.500€", "funding": "Bis zu 15%"}]',
    FALSE
);
