// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdgrhdvtwcohtzwfaawo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZ3JoZHZ0d2NvaHR6d2ZhYXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjE2NzAsImV4cCI6MjA2NTQ5NzY3MH0.oA_lsxo710uv1izB0dFEoUPjf0Zk9-ZeeTMnSwBeE4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);